### ISSUE TITLE
Normalize plot styles

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-v2.0-paper#103]
Right now, the plots have different fonts and styles. We should probably just use the matplotlib default settings.

**Comment by hamogu** [comment]
Not sure we need consistent plot styles. You can see that as a demonstration of the range of styles that are possible. However, I won't stop you if either of you feel the urge to change that.

**Comment by adrn** [comment]
I'm un-assigning myself because I'm totally oversubscribed this week and should focus on more pressing issues related to the paper. If anyone wants to take this on, go for it. Otherwise, I think the figures are fine as is.

**Comment by adrn** [comment]
(this can be closed on re-submission if not done)

**Comment by crawfordsm** [comment]
Closing
