### ISSUE TITLE
WCSaxis figure 

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#106]
Issue to discuss whether to continue to include the WCSaxis figure or if the RGB figure is sufficient on its own.

**Comment by astrofrog** [comment]
The WCSAxes figure specifically illustrates the ability to show multiple coordinate systems overlaid, and e.g. grid lines etc. Doing the same on the RGB figure might get in the way a bit of seeing the image? I personally don't see any harm in including both.

**Comment by hamogu** [comment]
Agreed with @astrofrog In the past, I've argued that we should keep the paper from growing too long, but in this case, I think two figures is OK. They are not too big, they look good, they won't take much reading time, and we don't pay extra for figures. Thus, I recommend leaving both and closing the issue.

**Comment by adrn** [comment]
Fine by me.
