### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-v2.0-paper#139]
The referee says

> More generally, given the technical nature of the work being described here, I frequently found myself wanting a small code snippet that demonstrated the new/improved functionality of the packages being described. Perhaps the authors could find a way to include short code examples where appropriate, either inline in the paper body or in the appendix.

We discussed this in the paper telecons at least once and decided that we don't like code snippets too much because (i) then can be found in the docs, (ii) they risk being version specific and could be almost out of date already when the paper is published, and (iii) they are not necessarily instructive unless you are an astropy user already and know the context well enough to fill in the missing lines (or you get very long examples).

As a compromise, I suggest that we pick no more than 5 examples with no more than 5 lines of code each. I think that these do *not* have to be self-contains and executable, e.g. say ``data=Table.read(''sourcelist.fits")`` without downloading an actual file with a persistent identifier etc.

Note that scripts for exporting code examples with syntax highlighting to pdf (to be included as a figure) exist in the repro for paper I.

**Comment by bsipocz** [comment]
If we can write up nicely the arguments why we choose not to have examples, I'm all for that and rather point the reader to the documentation, if needed at multiple places.

**Comment by crawfordsm** [comment]
Comment from @eteq:

> I think our philosophy is that we don't want snippets that duplicate/are separate from the docs. So how do we want to finesse this? We could point to specific URLs with these snippets where the referee asks. Or just copy-and-paste them into the paper...? It's probably a good point that if there aren't examples in the docs, we should add them, though.

**Comment by crawfordsm** [comment]
Since the referee specifically asked about this, I would agree with adding a few select code examples.  I would thinking coordinates, modeling, and visualization might be the three places (for the visualization, we should probably add a link to the codes into the paper to make those easily accessible).

**Comment by crawfordsm** [comment]
@adrn can you lead adding some code examples for these sections? Especially coordinates?

**Comment by bsipocz** [comment]
I'm still with @eteq's comment above, that we should try to avoid adding code snippets in the paper and rather point to the docs, and explain the philosophy that there are no snippets as they may be out of date in a few years time, etc.

**Comment by adrn** [comment]
I'm very much against it, but I can add a short example to coordinates. I'm definitely not the right person to make a modeling example though! Can someone else take on modeling?

**Comment by hamogu** [comment]
I also don't really like code examples. together with @eteq @bsipocz and @adrn. @crawfordsm did not advocate it either. So, how about we add a discussion to the reply to the referee why we do **not** include code snippets? If all goes well, we convince the referee, if not he'she can always send te paper pack and then we add some examples in the next round. It's OK to disagree wit ha referee on one or tow points, I think. We'll implement almost all other suggested changes.

**Comment by bsipocz** [comment]
I agree with @hamogu, let's try not to include examples. Not because we can't include them, but because we don't want to. If they insist we can still throw-in a few.
