### ISSUE TITLE
Comment from Wolfgang

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#14]
This was left on the overleaf draft (which is now hopefully locked), but here was a comment from @wkerzendorf left there before I locked it: 

\inlinecomment{Wolfgang K}{I would get more quickly to the point here (I think we can also cut some more if needed): Software is a crucial component of modern research. The use of software ranges from single-use scripts used by individuals to extensive frameworks supported by large institutions. Despite their different scopes they share common algorithms. One of the core goal of \astropypkg is to provide such common algorithms for \textsc{python} packages. The other is to foster a community glued by open-source principals. }All astronomical research makes use of software in some way.  Astronomy as a field has thus long supported the development of software tools

**Comment by adrn** [comment]
@wkerzendorf - if you still feel this should be addressed, could you please open a PR with a suggested rewrite?

**Comment by wkerzendorf** [comment]
This was the suggested rewrite of the first paragraph. I'm not sure if you want this kind of rewrite now - or mainly minor changes (am happy with either). Will make a PR - if I wouldn't distract with it - let me know.: 


Software is a crucial component of modern research. The use of software ranges from single-use scripts used by individuals to extensive frameworks supported by large institutions. Despite their different scopes they share common algorithms. One of the core goal of \astropypkg is to provide such common algorithms for \textsc{python} packages. The other is to foster a community glued by open-source principals.

**Comment by adrn** [comment]
No strong feelings either way for me so I defer to @crawfordsm!

**Comment by crawfordsm** [comment]
I like some of your rephrasing, and so a PR would be best and we can discuss it further there--I just didn't want your edits getting lost as I think it was a good point which is why I opened an issue.  We are going to distribute a draft tonight to everyone, and so it might not get merged until after that, but it would still be good to have.  

Thanks for the edits @wkerzendorf

**Comment by wkerzendorf** [comment]
@crawfordsm I just downloaded the newest version - and the introduction has been rephrased very similar to what I suggested - I think that is great. I have another read of the paper and see if there are any other changes.
