### ISSUE TITLE
Warning for LS periodograms

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-v2.0-paper#141]
From the referee's report:

> Note from statistical editor. In sec 3.11.3, a sentence can be added warning users about difficulties in interpreting the statistical significance of Lomb-Scargle periodogram peaks. This is important because unreliable interpretation is common, and warnings are not given elsewhere (e.g. NASA Exoplanet Archive Periodogram Service). A good reference is Vanderplas 2017 (https://arxiv.org/abs/1703.09824) soon to appear in the ApJ Suppl. 

I don't think this is a controversial suggestion, I just wanted to make an issue for it so we don't forget because it is listed with the other "major points".

**Comment by crawfordsm** [comment]
cc:  @jakevdp -- just in case you aren't familiar with this citation

**Comment by jakevdp** [comment]
I could definitely be persuaded to cite Vanderplas 2017 here :smile:

**Comment by crawfordsm** [comment]
@jakevdp can you add some text by 28 Feb?  You can either include your response to the referee in the comment to the PR or directly in the file response.txt

**Comment by adrn** [comment]
I think this was fixed in #149!
