### ISSUE TITLE
Decide if more code snippets are called for

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-v2.0-paper#143]
From the referee:

> More generally, given the technical nature of the work being described here, I frequently found myself wanting a small code snippet that demonstrated the new/improved functionality of the packages being described. Perhaps the authors could find a way to include short code examples where appropriate, either inline in the paper body or in the appendix. 

I think our philosophy is that we *don't* want snippets that duplicate/are separate from the docs.  So how do we want to finesse this?  We could point to specific URLs with these snippets where the referee asks.  Or just copy-and-paste them into the paper...?  It's probably a good point that if there *aren't* examples in the docs, we should add them, though.

**Comment by bsipocz** [comment]
This somewhat overlaps with https://github.com/astropy/astropy-v2.0-paper/issues/139. I said there, already that (as we discussed it several times during writing up) it would be great if we could get away without adding any code examples to the paper, either by stating this principle somewhere in the paper, or point to the documentation more.

**Comment by crawfordsm** [comment]
Closing in favor of #139
