### ISSUE TITLE
Update affiliated package table

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-v2.0-paper#146]
The "provisionally accepted" table is no longer relevant as we don't have a provisional category anymore. Also, the main table of packages should be updated as I think there are a couple of recent additions.

**Comment by adrn** [comment]
I can do this.

**Comment by astrofrog** [comment]
Ok :) Don't forget to remove the provisional table! (since I see you changed the title of the issue)

**Comment by bsipocz** [comment]
@adrn - If you want something off your hand, probably this is the one I can take over the best.

**Comment by adrn** [comment]
Sold!

**Comment by bsipocz** [comment]
Most of this is done, where the wasn't DOI-d reference available, I cited the github url instead.
