### ISSUE TITLE
Table 1 as matrix

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#15]
@perrygreenfield commented:

Wouldn't the table be better represented as a matrices? Or perhaps as a matrix as a crude image with colors or intensities representing the size of the quantity. Is the difference between median and mean significant enough to warrant showing both? A link to the actual numbers may satisfy readers that want the exact values, but I suspect the majority don't need to see that precision.

**Comment by ycopin** [comment]
:+1:

**Comment by astrofrog** [comment]
Maybe the maximum value are enough, in which case matrix form should be easy

**Comment by hamogu** [comment]
Agreed that max value would be enough.

**Comment by lgbouma** [comment]
Also relevant: it might be more sensible (whether in table or matrix form) to give the values in scientific notation.

For example, does "0.000" mean they agree down to machine precision? Surely not.

**Comment by adrn** [comment]
@hamogu Now we have Table 1 and Figure 3 - do we need both?

**Comment by hamogu** [comment]
We don't *absolutely need* both, but there is nothing wrong with having both in my opinion. We could add a colorscale to the figure, that would make the table obsolete I think.

**Comment by bsipocz** [comment]
👍 to keep only the figure and the link to the benchmarks for those who need more details. The paper already very coordinates heavy, so it's good to cut back on repetition.
