### ISSUE TITLE
Plot of contributors over time

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#150]
The referee has asked to include a plot of number of reviewers over time in the inline comments:

> REVIEWER: What about the number of contributors over time? I’ve seen this
> plot elsewhere and it might be useful to show here.
>

**Comment by adrn** [comment]
I think I made a version of this at some point, so I can do this.

**Comment by bsipocz** [comment]
There is a "contributors per month" plot, something similar to that one may be useful for addressing #151, too?
https://www.openhub.net/p/astropy
