### ISSUE TITLE
Mark up changes for referee

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-v2.0-paper#153]
ApJ requires that changes compared to the original text are highlighted on resubmission. They strongly suggest, but to not formally require, marking modified text in bolt font and the latex template provides some macros to help with that.

I'm not sure we want to add those to every PR right now, but if we don't we'll have to generate that markup somehow. 
I suggest the "latexdiff" script between the original submission and the resubmission. We could than upload a pdf with all those markings separately. I have never done that (I usually just that textbf manually), but it might work well in this context. 
Thought?

**Comment by crawfordsm** [comment]
I think doing this automatically would make sense as I don't think we have been consistently marking changes so far.

**Comment by bsipocz** [comment]
running a latexdiff between the submitted and resubmitted version seems the best solution to me too.

**Comment by crawfordsm** [comment]
done in the submitted version
