### ISSUE TITLE
Citation for CI helpers

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#156]
The reviewer asked for a citation for the following statement:

> While the current development is mostly driven by the needs of the Astropy ecosystem, the actual usage of this package is extremely widespread.

cc: @bsipocz

**Comment by bsipocz** [comment]
Would you think it's enough to respond to this without any change to the main text? I have two points that I based this claim on:

* ~30% of the ci-helpers contributor are not coming from the astropy (or even the broad openastronomy) community:
https://github.com/astropy/ci-helpers/graphs/contributors

* There are currently 292 repositories on github that has ci-helpers in their travis configuration file. That is way much more than the Astropy Project and include repositories from organizations such as ContinuumIO, Anaconda-Platform, spyder-ide, mne-tools, pytest-dev, MDAnalysis

 https://github.com/search?utf8=%E2%9C%93&q=filename%3A.travis.yml+%22astropy%2Fci-helpers%22&type=

**Comment by crawfordsm** [comment]
Closed wtih commit 7662bb2
