### ISSUE TITLE
Classes, decorators, mixin, namespace

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#18]
@perrygreenfield comments: 
Agreeing with Tom below, I would avoid using terms like subclass, decorators, mixin, namespace, (and perhaps even class, instead using objects consistently; this is no place to be pendantic about the distinction between classes and objects; even to the extent of adding a qualifying sentence somewhere like: "In this paper we will use object when we mean object or classes; in software there are important distinctions between the two terms, but they are not relevant in this paper."), and the like and replace them with more generic descriptions, e.g., "extended", or "tools to make defining functions that can use quantities simple to write"

**Comment by crawfordsm** [comment]
I've removed mixin and namespace and decorators and subclasses where it was not necessary, but I'm leaving it as an open question where to remove  `class` as well.   I would like to hear other's thoughts about it.

**Comment by adrn** [comment]
My own feeling is no on removing "class" -- if we're going to keep in the word "function," I think we should be able to say "class" as well.

**Comment by hamogu** [comment]
I'm all for removing "class". "Function" is not just a computer-science term, it's a mathematical thing as in `f(x) = 3 * x + 5` and this will be understood by every reader. "Class" on the other hand only makes sense in programming.

**Comment by bsipocz** [comment]
I'm with @adrn here, "class" is basic enough that the reader can very well learn about the existence of the concept from the paper. I'm referring back to my other comment, we don't consider dumbing down a science paper, why should we do that here? 

I assume the reader who actually considers reading through the 30 pages is willing to learn something from it, and doubt the rest who we try to optimize for here will read it anyway.

**Comment by hamogu** [comment]
As a compromise, how about adding a few words like "A class a basic feature of many object-oriented programming languages". I just tired to find "class" on wikipedia. There are about a dozen meanings of "class", but the OOP is not one of them. (And I would expect cosmology papers to give a reference or few words of explanation when they start talking about NFW profiles, too.)

**Comment by bsipocz** [comment]
Adding that sentence sounds good to me.

(btw this comes up close to the top when googling https://en.wikipedia.org/wiki/Class_(computer_programming) )

**Comment by taldcroft** [comment]
:+1: for keeping "class" in the paper.

**Comment by crawfordsm** [comment]
Class stays, but decorator, namespace, and mixin have been removed
