### ISSUE TITLE
glossary

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#19]
We should consider adding a glossary of terms that are not common to the non-coding astronomer

**Comment by adrn** [comment]
I'm not sure about this. Probably better to just try not to use such terms!

**Comment by hamogu** [comment]
Or explain them in the text when they are used.

**Comment by bsipocz** [comment]
A glossary in a paper feels a bit patronizing, I'm sure non coding astronomers are capable of googling up terms that are not explained in the text. There is no glossary in cosmology papers either, even though I'm pretty sure many of the stellar astronomers are not familiar with some of the terms they are using.

**Comment by hamogu** [comment]
3:1 statements think a glossary is not a good addition in this case. Closing.
