### ISSUE TITLE
Citations in Sphinx extensions

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#22]
TPR commented: 

We should put the releases of sphinx-automodapi on Zenodo and cite this

**Comment by astrofrog** [comment]
This is very minor and can be done after the paper is sent out to everyone. I need to fix something in the sphinx-automodapi repo before doing this.

**Comment by adrn** [comment]
I pinged @astrofrog in slack.

**Comment by hamogu** [comment]
@astrofrog : Any progress on this? It's the last issue on the "definitely fix before submission" list.
