### ISSUE TITLE
Check consistent use of astropy

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#25]
Is astropy used correction through the paper?  Either \astropypkg or \astropy ?  

Check prior to distributing paper.

**Comment by ycopin** [comment]
Please check also versioning, e.g. "v2.0" vs. "version 2.0" vs. "version v2.0".

**Comment by pllim** [comment]
I caught a wild "Astropy" in #70. FYI.

**Comment by pllim** [comment]
> Either \astropypkg or \astropy ?

@crawfordsm , I think I have caught all of those (only 2 instances or so needed fixing). However, I am not sure whether these are also meant to be used inside a section or sub-section title; Probably not? What about for "astropy" wording inside an emphasis tag?

**Comment by crawfordsm** [comment]
The key thing is to be consistent -- so no to section titles and if it is inside a tag, it should probably keep the formatting of the tag

**Comment by pllim** [comment]
I do remember seeing things like `\astropy` in *some* section titles but not all, so I don't think it is quite consistent in that respect yet. You might want to sweep through it again.
