### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#31]
The table section could be expanded:

@adrn: Need more introduction to the table subpackage!

@perrygreenfield: Some mention that some of these are inspired by Pandas?

**Comment by hugobuddel** [comment]
The nddata/table section seemed inspired by Pandas, at least that's what popped up in my mind. But there was no reference to Pandas and I wondered how they compare. So maybe a Pandas reference would be useful, but not essential.

**Comment by hugobuddel** [comment]
I don't understand this:

> The \texttt{Table} object now allows \texttt{Quantity} objects, celestial
> coordinate objects [...] to
> be used as columns, and also provides a general way for other user-defined
> objects to be used as columns.

Is the idea that those objects can be used as table-cell-values with the object type as column-type? That's the only logical thing that I can make of this, but that doesn't seem to be what is said.

A column is like a whole list of values (like astropy 'Column' class), so how can a Quantity object be used as a column? Or maybe I misunderstand.

Not sure how to improve the phrasing though... (I'm just going through the paper as a minor astropy contributor and decided to add feedback directly where it might be relevant.)

**Comment by taldcroft** [comment]
@hugobuddel - see http://docs.astropy.org/en/v2.0.2/table/mixin_columns.html for a longer explanation.

It might be worth adding "array-valued" to clarify:

 The \texttt{Table} object now allows *array-valued* \texttt{Quantity} objects, celestial
 coordinate objects [...] to
 be used as columns, and also provides a general way for other user-defined
*array-like* objects to be used as columns.

**Comment by hugobuddel** [comment]
Adding "array-valued" makes sense indeed. The Quantity section does not mention the possibility of array-like quantities (maybe because they are not new?), so it was not obvious that (only) array-like quantities are intended here.

**Comment by pllim** [comment]
I noticed that the two sub-sections of "Tables" are actually at the same level -- 3.5.3 and 3.5.4 should have been 3.5.2.1 and 3.5.2.2, if you get what I mean.
