### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-v2.0-paper#34]
Hi, I noticed a small technical issue: when I open the PDF on my Mac in the Preview or Acrobat Reader app, the text appears very un-sharp. I've never seen this with other papers. Here's a screenshot:

![screen shot 2017-11-23 at 08 58 23](https://user-images.githubusercontent.com/852409/33162992-87283c24-d02c-11e7-8da7-aa7ecea6ead5.png)

Does anyone else see the same thing? Is it possible to change something to get a font that nicely renders on these common PDF viewers?

**Comment by ycopin** [comment]
Same here, using Acrobat under Linux. IIRC, this is the default behaviour of pdflatex, this can be temporarily solved with ```\usepackage{lmodern}```, but this is ultimately handled by the editor.

**Comment by adrn** [comment]
I don't see this. When I open with Preview on a mac with OS X Sierra (10.12.6) I see:

![image](https://user-images.githubusercontent.com/583379/33399675-79be8d78-d521-11e7-93db-1bee5841c33c.png)

**Comment by sladen** [comment]
FWIW, with Evince on Ubuntu, these bitmap-style rendering artifacts are visible:
* On the rotated (landscape) pages near the end
or, with the document rotated 90-degrees:
* On all pages, except the rotated (landscape) pages near the end

Didn't immediately find a solution, but possibly some unique hinting/scaling interaction, or something else that is causing a blending step prior (so leading to rasterisation) prior to rotation.  In short: dunno.

**Comment by adrn** [comment]
Ah I see the issue now - this is if you download the PDF that travis builds, right? Try cloning the repo and building the latex source (you can just type `make` in the repo).

I see the graininess when I download the Travis-built PDF, but *not* when I build locally. If that is the case for you too, I think we should close this.
