### ISSUE TITLE
Include software versions in Table 1

### ISSUE THREAD

**Issue by ycopin** [astropy/astropy-v2.0-paper#35]
Even though Table 1 is claimed to be illustrative only, it's quantitative: numbers probably depend on some specific software versions, which should be quoted.

**Comment by crawfordsm** [comment]
Something to note for updating Table 1 @astrofrog

**Comment by crawfordsm** [comment]
Will not address for the re-submission

**Comment by astrofrog** [comment]
Sorry for dropping the ball on this!
