### ISSUE TITLE
more astronomy focused Modeling introduction?

### ISSUE THREAD

**Issue by hugobuddel** [astropy/astropy-v2.0-paper#43]
The modelling capability is new for me, so I read it with interest. Here a suggestion to make it even more interesting to readers. (Feel free to ignore though, the section is already nice.)

Perhaps it can be elaborated on why the modelling is added to astropy at all? As in, what are the astronomical drivers to have modelling in an astronomy package? Why did we not use/wrap/wrote a general modelling package instead?

From the rest of the section I can guess, e.g. that a varying-over-the-FoV-PSF-model is a typical astronomy thing, or that we want to use Quantity objects, etc. Perhaps we can put the astronomy-specific 'why' at the start of the Modeling section?

(Also, it isn't really necessary to have a subsubsection (3.7.1) called 'Overview'. That text can just be in subsection 3.7 directly I think.)

**Comment by pllim** [comment]
@nden and I discussed about "what are the astronomical drivers" when it was written, however we decided to keep things brief, as `modeling` can be used for so many things that mentioning one but leaving the other out would do more harm than good. And to include everything is quite impossible. However, if you have an idea on how to do this, please do open a pull request by Dec 8. And Nadia, please correct me if I misremembered our discussion.

I do agree that Overview is unnecessary, so I'll remove it.

**Comment by hugobuddel** [comment]
It seems that some justification would be warranted though. As in, it should be trivial for the reader to answer "why am I reading this?", which for this paper translates to "why is this in astropy?". What problem is being solved in this section of the paper? Answers to these questions can be given on multiple levels, e.g. from an scientific or a technical perspective, preferably both. Currently you have to read between the lines to figure out the answers.

Being unfamiliar with the modeling functionality, my thoughts went sort-of as follows. Surely there must be existing python packages for modeling, so why are they not used? Are they not suitable for astronomy? Do they not fit in with the astropy framework? Why couldn't they be adapted? Or maybe there were no existing modeling packages at all? Wasn't it feasible to generalize the modeling to be a generic (non-astronomy specific) Python package (like emcee is for MCMC)? A non-astronomy reader (or a beginner) would even start with asking 'why is modeling relevant to astronomy (/to me) at all?'. Lure the reader in by spoon feeding them why they should care.

I can't write such an introduction paragraph myself since I don't know the answers to most of the above questions. Maybe it is too late to add such a paragraph though, and the text that is there is quite readable (and one of the most interesting sections to me), so it might be okay to leave it as it is.

**Comment by hugobuddel** [comment]
Note that similar why-questions could be asked for other sections of the paper, but to lesser extent in my opinion. E.g. surely quantities and units would be relevant outside astronomy, so why reinvent the wheel? But there one could ague--although this is not done explicitly--that astronomy has very specific requirements for quantities and units (like magnitudes) and that they are such an integral part of the system that they warrant an astropy-specific implementation. The implicit justification is a bit harder for the table section, why not simply use/wrap Pandas or something like that? Probably because of reasons. So I also commented on an issue related to that.

The ["Start with Why" talk from Simon Sinek](https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action) apparently influenced me quite a bit. He explains that most people start with what they did and how, while it would be better to explain the dreams you're trying to achieve first (the why).

**Comment by nden** [comment]
@hugobuddel @pllim 

What do you think about adding text to the first paragraph of modeling, so that it becomes:

```
Tha astropy.modeling subpackage provides a framework for representing
analytical models and performing model evaluation and parameter fitting.
The main motivation for it was creating a framework
which allows arbitrary combination of models to support a generalized World
Coordinate System package. The current FITS WCS model lacks the flexibility to represent
arbitrary distortions and does not meet the needs of many types of current instrumentation.
The addition of units to modeling made it attractive for representing
and fitting astrophysical models.

Models and fitters are independent of each other: a model can be fit with different
fitters and new fitters can be added without changing existing models. The
framework is designed to be flexible and easily extensible. The goal is to have
a rich set of models but also make it easy to create new ones if necessary. The
modeling framework is used in a variety of data analysis tools and is the basis
for the Generalized World Coordinate System (GWCS)
```

@hugobuddel Thanks for the link to that talk!
