### ISSUE TITLE
Re-export 'convolution-example.png' as PDF with machine readable text

### ISSUE THREAD

**Issue by sladen** [astropy/astropy-v2.0-paper#48]
_From @sladen on November 30, 2017 12:12_

Currently 'figures/convolution-example.png' contains pre-rendered text.  This could probably be easily re-exported as PDF containing bitmaps + machine readable/renderable text.

(Unfortunately this also appears to be the only image without source code to regenerate it, which possibly explains why this has not been done already).

_Copied from original issue: astropy/astropy#6917_

**Comment by sladen** [comment]
_From @bsipocz on November 30, 2017 12:39_

Wrong repo, presumably you refer to the figure in the paper here.

**Comment by sladen** [comment]
Working through with `git blame`—@adrn was this a part you wrote, or was it just the import?

**Comment by bsipocz** [comment]
the convolution part was originally written up by @keflavich, the git history we brought over from overleaf can be rather inaccurate.

**Comment by keflavich** [comment]
The png is taken directly from the astropy docs - it's generate there.  We can definitely make a pdf...

**Comment by pllim** [comment]
While we're discussing Figure 3 here, I have some feedback:

* Is the order of `(a)`, `(b)`, `(c)`, and `(d)` a standard thing in journals? I don't see any a, b, c, or d actually marked in the sub-figures. Therefore, I have to guess, which isn't hard in this case but any guessing isn't a good sign on the clarity of the caption.
* I see the usage of `x's` (apostrophe before the plural "s") and `NaNs` (no apostrophe) right next to each other in the caption. That somehow bothers me. But maybe this is a larger issue of consistent use of such apostrophe throughout the paper (should I open a new issue)?

**Comment by keflavich** [comment]
On plural letters:
https://english.stackexchange.com/a/25280/15719

a/b/c/d could be changed to top left/top right/bottom left/bottom right, or we could add them to the figure

**Comment by crawfordsm** [comment]
@keflavich If this can be updated by 13 Dec, that would be great.  Otherwise, there is no rush to fix this prior to resubmission if necessary.

**Comment by keflavich** [comment]
This should be resolved by #91.
