### ISSUE TITLE
accuaracy of coordinate transforms

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy-v2.0-paper#53]
NOVAS package is mentioned in text but is not in Table 1. 
I also wonder if table 1 info might be better presented as a figure.

**Comment by adrn** [comment]
Figure 3 now visualizes the data from Table 1, but don't know about NOVAS

**Comment by adrn** [comment]
Oh, I think NOVAS doesn't implement the transformation we plot in the figure (formerly the table). I've added a note to clarify.
