### ISSUE TITLE
Doc link: stable -> 2.0?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#57]
While reading the draft, a thought occurred to me: When this paper is out, "stable" might already be pointing to 3.0 and not 2.0. Therefore, is it possible to make a "2.0" (or "2.x") URL for the doc now and then change all the "stable" links to something like `http://docs.astropy.org/en/stable/v2.0/...`?

**Comment by bsipocz** [comment]
good point! I would definitely leave the generic links to "stable" (e.g. installation), but maybe we should indeed point to 2.0.x for anything submodule related.

**Comment by adrn** [comment]
I think the links conform to this in the current draft!
