### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy-v2.0-paper#58]
Figure may not be meaningful to those who don't know what all of the various acronyms mean: include a reference in caption?  Need to explain significance of the arrows coming out of and going back into a given oval?

**Comment by pllim** [comment]
> Need to explain significance of the arrows coming out of and going back into a given oval?

Could that be a manifestation of astropy/astropy-helpers#276 . I agree that it does not make sense and perhaps could be removed with Photoshop magic for the paper.

**Comment by ayshih** [comment]
The arrows coming out of and going back into a given oval represent real transformations where the starting and ending frames are the same, but some other attribute (e.g., observation time or equinox time) is different.

**Comment by adrn** [comment]
Yes, what @ayshih says is right - the arrows that loop back are real transformations that involve a change of frame attribute within the same frame class. It might be too much to explain this in the caption, but I could - what do you think @PBarmby ?

**Comment by hamogu** [comment]
I agree that this figure os not good for this context. Also, for this paper, it's not important to have different arrows have different colors
