### ISSUE TITLE
Back up performance increase claim with asv results?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#59]
In Section 3, "*Beyond what is mentioned below, most subpackages have seen increased performance since the release of the v0.2 package.*"

Is it possible to back up the claim above with a footnote that is perhaps an URL to appropriate `asv` results?

**Comment by bsipocz** [comment]
but we don't have benchmarks for all subpackages, do we?

**Comment by bsipocz** [comment]
otherwise 👍

**Comment by pllim** [comment]
No, not all sub-packages. Do partial proofs help? Benchmarking code (not the resulting plots) are at https://github.com/astropy/astropy-benchmarks/tree/master/benchmarks

**Comment by bsipocz** [comment]
well, not sure we really need the proofing, "most packages" cover the odd one that may not had performance improvement, and anyway, "because we say so" should be enough :trollface:

**Comment by pllim** [comment]
I was just thinking aloud when I opened this issue, so feel free to close if this is not worth pursuing. 😄

**Comment by crawfordsm** [comment]
I think it will be out of scope for this paper and as v3.1 will be focused on performance increases, it will be better for  more detailed analysis there.
