### ISSUE TITLE
Sec. 3.9.4 and figure 5

### ISSUE THREAD

**Issue by terben** [astropy/astropy-v2.0-paper#62]
- Could you say in which sense the Lupton algorithm to produce colour images is optimal?
- Figure 5 should contain axes such as Fig. 4. It is not really clear to me what this figure should show. If we want to demonstrate the colour-figure capabilities of ```astropy.visualization```, the example is probably not very good. A set of three or four panels which shows colour composite  images with different scalings offered by ```astropy.visualization``` would be better in my opinion.

**Comment by pllim** [comment]
If I may add, if we decide to keep the existing Figure 5, an URL to SDSS source or a citation to relevant publication would be nice.

**Comment by crawfordsm** [comment]
Thanks for the comment @terben -- the Lupton et al. paper that is cited there goes into detail about why it is optimal and comparisons of rgb techniques is out of scope for this paper.   

However, we should add a link to the skyserver or citation to it.

**Comment by hamogu** [comment]
I agree with @crawfordsm : The link to the Lupton paper show be sufficient to back up the word "optimal".
