### ISSUE TITLE
Figure 4 could include a link to source code so readers could practice/recreate the image

### ISSUE THREAD

**Issue by adeleplunkett** [astropy/astropy-v2.0-paper#65]
This figure is very nice. It would be of great use to the community (and maybe citable) if the code were available to make this plot. Is it possible to link to a github page or python notebook where the code is available to recreate this figure?

I understand if this is *extra/unnecessary* work.

**Comment by bsipocz** [comment]
There is one of such figure in the astropy documentation, including the source code.
