### ISSUE TITLE
astropy's vision and philosophy, can you include a link/reference?

### ISSUE THREAD

**Issue by adeleplunkett** [astropy/astropy-v2.0-paper#67]
You write (page 4): "to ensure they are in keeping with astropy's vision and philosophy." Is there any place that the vision and philosophy are listed, that you can reference here?

**Comment by bsipocz** [comment]
maybe we need a link to astropy.org somewhere in the intro, but the affiliated package section later on details these out.

**Comment by hamogu** [comment]
There is no reference for this; astropy has not published a document called "vision and philisophy" or similar. Instead, I think that refers to the goals for the astropy project that are taken up in several parts of the paper, starting from the introduction (reusability of code, docs, testing, continuous integration, ...). Do you have a better idea how to say this?

**Comment by bsipocz** [comment]
@hamogu - If that's a question for me, then no, I have no better way to say it than it's currently done in the paper, only to add a link to astropy.org somewhere in the beginning (where this vision of reuse/document/test/CI is also mentioned)

**Comment by adrn** [comment]
Don't we have a "vision" section of the documentation?
http://docs.astropy.org/en/stable/development/vision.html

I'll add a footnote link to this in the paper.
