### ISSUE TITLE
Avoid orphaned subsection title?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#78]
Not sure how particular journal editor would be about this... Note that Section 3.5.5 title is orphaned, i.e., last sentence of the page. Of course, this might change as the paper gets more edits, however know that such a thing is possible. 

![untitled](https://user-images.githubusercontent.com/2090236/33751325-2d39483e-dba8-11e7-949c-99955e0de112.png)

**Comment by adrn** [comment]
Not something we have to deal with - (a) the paper will be edited more, so lengths will change, and (b) the journal will reformat the paper.
