### ISSUE TITLE
Why some sentences have spaces around "/"?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#80]
I see a both ways "/" is used in the paper:

1. "blah / blah" (with spaces)
2. "blah/blah" (no spaces)

Should we choose one and stick with it? Does it matter?

**Comment by hamogu** [comment]
If somebody want to homogenize that and knows what the officially correct way is, that's fine. However, I think it's a waste of time at this stage. Every accepted paper in ApJ goes through professional language editing by ApJ staff and they will change these things to match the journal standard.

**Comment by adrn** [comment]
Agreed. I think this should be up to the AAS journals editors.
