### ISSUE TITLE
Citation for Aitoff projection?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#81]
I, for one, have no idea what it is, so a citation would be helpful if I want to read more about it.

p.s. I found https://en.wikipedia.org/wiki/Aitoff_projection but I don't think Wikipedia links look nice on a paper.

**Comment by adrn** [comment]
I think it's a pretty standard projection and other papers that use the phrase don't seem to cite anything: https://ui.adsabs.harvard.edu/#search/q=%20full%3A%22aitoff%22&sort=date%20desc%2C%20bibcode%20desc

**Comment by pllim** [comment]
Haha, okay, it's just me then. Never mind. :wink:
