### ISSUE TITLE
Inconsistent figure captions handling

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#82]
I see a mix of these styles in the paper:

* Caption has most of the explanation of the figure. While in the main text, it is very brief like, "See Figure X."
* Caption is very brief. While in the main text, it explains the figure in detail.

If you don't think this is worth addressing, feel free to close the issue.

**Comment by crawfordsm** [comment]
When reviewing the paper, it would be good to check consistent captions between the different figures

**Comment by hamogu** [comment]
Not a big deal though. Many papers mix these styles, depending on what's on the figure and how it fits the flow of text in the paragraph.

**Comment by adrn** [comment]
I think mixing the styles is fine and the current captions seem ok for now. Let's revisit this if the referee also comments on this.
